### ISSUE TITLE
Client freezes while connecting to ocis

### ISSUE THREAD

**Issue by mike-lloyd03** [owncloud/client#11129]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

When attempting to log in to my OCIS server, the initial window "What is your server's address?" disappears after entering the URL. The main window stays open but appears frozen. No mouse or keyboard events are recognized.

Looking at the client logs, it appears that the server is not sending the `registration endpoint` URL when it attempts to authenticate.

I am running OCIS v3.0.0 using Docker.

Docker compose file:

```yaml
version: "3"

services:
  ocis:
    image: owncloud/ocis:3
    entrypoint:
      - /bin/sh
    command: ["-c", "ocis init || true; ocis server"]
    env_file: .env
    environment:
      OCIS_URL: ${OCIS_URL}
      OCIS_LOG_LEVEL: info
      OCIS_LOG_COLOR: true
      PROXY_TLS: "false"
      OCIS_INSECURE: "false"
      PROXY_ENABLE_BASIC_AUTH: "true"
      IDM_ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
      IDM_CREATE_DEMO_USERS: "false"
    volumes:
      - /mnt/data/owncloud/config:/etc/ocis
      - /mnt/data/owncloud/data:/var/lib/ocis
    logging:
      driver: "local"
    restart: always
    ports:
      - 9200:9200

```

### Expected behavior

Should generate link to authenticate with browser.

### Logs

Client Logs:

```
23-08-17 22:57:48:585 [ debug sync.credentials.oauth ]  [ OCC::OAuth::startAuthentication ]:    starting authentication
23-08-17 22:57:48:585 [ debug sync.credentials.oauth ]  [ OCC::OAuth::fetchWellKnown ]: fetching "/.well-known/openid-configuration"
23-08-17 22:57:48:586 [ debug setupwizard.controller ]  [ OCC::Wizard::SetupWizardController::changeStateTo ]:  Current wizard state: OCC::Wizard::SetupWizardState::CredentialsState
23-08-17 22:57:48:744 [ debug sync.credentials.oauth ]  [ OCC::OAuth::fetchWellKnown()::<lambda ]:      parsing .well-known reply successful, auth endpoint QUrl("https://ocis.my.server/signin/v1/identifier/_/authorize") and token endpoint QUrl("https://ocis.my.server/konnect/v1/token") and registration endpoint QUrl("")
23-08-17 22:57:48:744 [ debug sync.credentials.oauth ]  [ OCC::OAuth::startAuthentication()::<lambda ]: registration endpoint not provided or empty: QUrl("")
```

Server Logs:

```
ocis-ocis-1  | {"level":"info","service":"proxy","proto":"HTTP/1.1","request-id":"b042e8f2-9626-46bd-8020-46ce07bfeca8","remote-addr":"XX.XX.XX.XX","method":"GET","status":200,"path":"/.well-known/webfinger","duration":0.803456,"bytes":140,"time":"2023-08-18T03:57:48.558403948Z","line":"github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/accesslog.go:28","message":"access-log"}
ocis-ocis-1  | {"level":"info","service":"proxy","proto":"HTTP/1.1","request-id":"05518205-7d63-4bb1-81a4-ac961eb39cdf","remote-addr":"XX.XX.XX.XX","method":"GET","status":200,"path":"/.well-known/openid-configuration","duration":0.425368,"bytes":1802,"time":"2023-08-18T03:57:48.710297386Z","line":"github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/accesslog.go:28","message":"access-log"}
ocis-ocis-1  | {"level":"info","service":"auth-machine","pkg":"rgrpc","traceid":"00000000000000000000000000000000","time":"2023-08-18T03:58:12.308461083Z","line":"github.com/cs3org/reva/v2@v2.14.0/internal/grpc/services/authprovider/authprovider.go:141","message":"user idp:\"https://ocis.my.server\" opaque_id:\"5a4937b6-92bc-4f43-83be-164f2d9191bd\" type:USER_TYPE_PRIMARY  authenticated"}
ocis-ocis-1  | {"level":"info","service":"proxy","proto":"HTTP/1.1","request-id":"5120b133-ae58-4399-a25b-2cd4534627f0","remote-addr":"XX.XX.XX.XX","method":"GET","status":200,"path":"/ocs/v2.php/apps/notifications/api/v1/notifications","duration":3.410828,"bytes":72,"time":"2023-08-18T03:58:12.310523451Z","line":"github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/accesslog.go:28","message":"access-log"}
ocis-ocis-1  | {"level":"info","service":"proxy","proto":"HTTP/1.1","request-id":"4cadf0ab8c3c/sdSXtPmqLz-000086","remote-addr":"XX.XX.XX.XX","method":"GET","status":302,"path":"/signin/v1/identifier/_/authorize","duration":37.744752,"bytes":0,"time":"2023-08-18T03:58:28.347163345Z","line":"github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/accesslog.go:28","message":"access-log"}
ocis-ocis-1  | {"level":"info","service":"proxy","proto":"HTTP/1.1","request-id":"4cadf0ab8c3c/sdSXtPmqLz-000088","remote-addr":"XX.XX.XX.XX","method":"GET","status":200,"path":"/oidc-silent-redirect.html","duration":0.492546,"bytes":490,"time":"2023-08-18T03:58:28.581131326Z","line":"github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/accesslog.go:28","message":"access-log"}
ocis-ocis-1  | {"level":"info","service":"proxy","proto":"HTTP/1.1","request-id":"4cadf0ab8c3c/sdSXtPmqLz-000090","remote-addr":"XX.XX.XX.XX","method":"GET","status":200,"path":"/oidc-silent-redirect","duration":0.529676,"bytes":7683,"time":"2023-08-18T03:58:28.77588887Z","line":"github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/accesslog.go:28","message":"access-log"}

```

### Client version number

ownCloud 4.2.0 [f5a29b](https://github.com/owncloud/client/commit/f5a29bc3446734c565b106c1bdddc09ec03f76eb)
Libraries Qt 5.15.10, OpenSSL 3.1.1 30 May 2023
Using virtual files plugin: suffix
arch-6.4.3-arch1-1

### Desktop environment (Linux only)

Linux 6.4.3-arch1-1

### Client package version and origin (Linux only)

Installed from Arch Package Repository

### Server information

ownCloud | Infinite Scale
Community
3.0.0
7.0.0
