### ISSUE TITLE
Increased CPU usage and warn/err log spam with recent updates

### ISSUE THREAD

**Issue by C8opmBM** [owncloud/client#11476]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

I've been getting high cpu errors. 
This is the log (log level warn) getting constantly spammed over and over.
If I close the win client, the errors/wrn won't appear.

Using latest ocis-web server and win client (latest alpha 6.x)

### Expected behavior

No errors/warn. I've been using ocis - authelia setup for more than an year with minimal cpu usage (less than 0.5%)

### Logs

```
2024-01-16T22:34:35Z WRN core access token not set pkg=rhttp service=frontend traceid=121299601aac2ef8f1e2857dc0fffe5c
01/17/2024
12:34:36 AM
2024-01-16T22:34:36Z ERR cant get service account error="unexpected status code while authenticating service user: CODE_UNAUTHENTICATED" service=userlog
01/17/2024
12:34:36 AM
2024-01-16T22:34:36Z WRN http end="16/Jan/2024:22:34:36 +0000" host=127.0.0.1 method=GET pkg=rhttp proto=HTTP/1.1 service=storage-system size=0 start="16/Jan/2024:22:34:36 +0000" status=404 time_ns=409821 traceid=a54b9361238e9141b23b98d438db6e8c uri=/data/spaces/jsoncs3-share-manager-metadata%21jsoncs3-share-manager-metadata/users/9767076c-00b0-4124-ba33-1bcaa1a38ec4/received.json url=/users/9767076c-00b0-4124-ba33-1bcaa1a38ec4/received.json
```

### Client version number

ownCloud 6.0.0.12867-alpha.1
Also, until today I've been using the latest beta. Tried the alpha, but same behaviour,

### Server information

ownCloud | Infinite Scale
Community
5.1.0-prealpha+3cc485a0f
8.0.0-rc.1

**Comment by TheOneRing** [comment]
Looks more like an ocis issue?

**Comment by C8opmBM** [comment]
Unlikely, since closing desktop client stops the llog being spammed

**Comment by TheOneRing** [comment]
Please add some client logs https://doc.owncloud.com/desktop/next/appendices/troubleshooting.html#log-files , with http logs enabled.

**Comment by kobergj** [comment]
`5.0+` ocis version needs service accounts to be enabled. Did you set envvars `OCIS_SERVICE_ACCOUNT_ID` and `OCIS_SERVICE_ACCOUNT_SECRET` ? (or used ocis init on a fresh installation?)

**Comment by C8opmBM** [comment]
@kobergj I do not use the vars you mentioned. I've been running ocis since nov 2023, never needed them before. Yes I used _ocis init_ in my compose:

```
  owncloud:
    container_name: owncloud
    hostname: owncloud
    image: owncloud/ocis:latest
    profiles:
      - private
    networks:
      - ownmedia
    entrypoint:
      - /bin/sh
    command: ["-c", "ocis init || true; ocis server"]
    environment:
      DEMO_USERS: "false"
      PROXY_TLS: "false"
      OCIS_INSECURE: "true"
      OCIS_URL: ${OCIS_URL}
      PROXY_HTTP_ADDR: ${OCIS_PROXY_HTTP_ADDR}
      OCIS_LOG_LEVEL: warn
      OCIS_LOG_COLOR: "true"
      OCIS_LOG_PRETTY: "true"
      OCIS_LOG_TIMEZONE: ${TZ}

      OCIS_OIDC_ISSUER: ${OCIS_OIDC_ISSUER}
      WEB_OIDC_CLIENT_ID: ${OCIS_WEB_OIDC_CLIENT_ID}
      PROXY_OIDC_REWRITE_WELLKNOWN: "true"
      PROXY_OIDC_ACCESS_TOKEN_VERIFY_METHOD: none

      PROXY_USER_OIDC_CLAIM: "preferred_username"
      PROXY_USER_CS3_CLAIM: "username"
    expose:
      - 9200
    volumes:
      - ${CONFIGDIR}/ownCloud/config:/etc/ocis
      #- ${CONFIGDIR}/ownCloud/data:/var/lib/ocis
      - ${CLOUDDIR}/owncloud:/var/lib/ocis
    restart: unless-stopped
```

@TheOneRing - will prepare the logs tomorrow and post back. 
Thanks.
