### ISSUE TITLE
macOS: offer both, current and legacy package for online update via sparkle

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7753]
Currently a config/ownCloud.yml for our online updater offers only one package. Example
```
  macos:
    currentVersion: 2.6.1.13096
    currentVersionString: ownCloud Client 2.6.1 (build 13096)
    downloadUrl: https://download.owncloud.com/desktop/stable/ownCloud-2.6.1.13096.pkg.tbz
    minimumSystemVersion: 10.12.0
```

We also provide
https://download.owncloud.com/desktop/stable/ownCloud-osx10.11-2.6.1.13096.pkg.tbz
as a legacy build for 10.10 and 10.11 platforms.

Is there a way to tell sparkle to choose the correct one?
E.g. would a second entry 
```
    currentVersion: 2.6.1.13096
    currentVersionString: ownCloud Client 2.6.1 (build 13096)
    downloadUrl: https://download.owncloud.com/desktop/stable/ownCloud-osx10.11-2.6.1.13096.pkg.tbz
    maximumSystemVersion: 10.11.0
    minimumSystemVersion: 10.10.0
```
be possible so that 
* a legacy system receives ownCloud-osx10.11-2.6.1.13096.pkg and
* a modern system receives ownCloud-2.6.1.13096.pkg?
